#!/usr/bin/env python3
"""Download missing Countix videos from YouTube using yt-dlp.

This script reads missing_videos.csv, attempts to download the precise
segments from YouTube, and saves the video to videos/.
It implements random delays between downloads to avoid rate-limiting, 
and outputs a final_missing_videos.csv for any clips that still fail.
It immediately deletes any downloaded video if it is corrupted, 
ensuring no orphaned files are left on disk.
"""

import argparse
import csv
import json
import random
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path


SCRIPT_VERSION = "1.2"
SCRIPT_DIR = Path(__file__).resolve().parent

VIDEO_REPORT_COLUMNS = (
    "split",
    "youtube_id",
    "kinetics_filename",
    "expected_filename",
    "source_path",
    "reason",
)


@dataclass(frozen=True)
class MissingRequest:
    split: str
    video_id: str
    start: int
    end: int
    expected_filename: str
    kinetics_filename: str


@dataclass(frozen=True)
class MediaProbe:
    duration: float | None
    video_streams: int
    video_codecs: tuple[str, ...]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Download missing Countix clips from YouTube."
    )
    parser.add_argument(
        "--missing-csv",
        type=Path,
        default=SCRIPT_DIR / "missing_videos.csv",
        help="Path to the missing_videos.csv file generated by the first script",
    )
    parser.add_argument(
        "--videos-dir",
        type=Path,
        default=SCRIPT_DIR / "videos",
        help="Video output directory (default: <script_dir>/videos)",
    )
    parser.add_argument(
        "--reports-dir",
        type=Path,
        default=SCRIPT_DIR,
        help="CSV report directory for final_* files (default: <script_dir>)",
    )
    parser.add_argument(
        "--min-delay",
        type=float,
        default=4.0,
        help="Minimum delay in seconds between YouTube requests",
    )
    parser.add_argument(
        "--max-delay",
        type=float,
        default=9.0,
        help="Maximum delay in seconds between YouTube requests",
    )
    return parser.parse_args()


def compact_error(text: str, limit: int = 1200) -> str:
    cleaned = " ".join(text.strip().split())
    return cleaned[-limit:] if cleaned else "unknown error"


def probe_media(path: Path, ffprobe: str) -> MediaProbe:
    command = [
        ffprobe,
        "-v",
        "error",
        "-show_entries",
        "format=duration:stream=index,codec_type,codec_name,duration",
        "-of",
        "json",
        str(path),
    ]
    result = subprocess.run(command, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(f"ffprobe failed: {compact_error(result.stderr)}")
    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError("ffprobe returned invalid JSON") from exc

    streams = payload.get("streams", [])
    video_codecs = tuple(
        str(stream.get("codec_name", "unknown"))
        for stream in streams
        if stream.get("codec_type") == "video"
    )
    duration_value = payload.get("format", {}).get("duration")
    try:
        duration = float(duration_value) if duration_value is not None else None
    except (TypeError, ValueError):
        duration = None
        
    return MediaProbe(
        duration=duration,
        video_streams=len(video_codecs),
        video_codecs=video_codecs,
    )


def write_report(
    path: Path,
    columns: tuple[str, ...],
    rows: list[dict[str, str]],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        writer.writerows(rows)
    temporary.replace(path)


def download_clip(
    yt_dlp: str,
    video_id: str,
    start: int,
    end: int,
    output_path: Path
) -> None:
    """Download a specific segment from YouTube using yt-dlp."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = output_path.with_name(f".{output_path.stem}.downloading{output_path.suffix}")
    if temporary.exists():
        temporary.unlink()

    url = f"https://www.youtube.com/watch?v={video_id}"
    
    command = [
        yt_dlp,
        "-f", "bestvideo[ext=mp4]/best[ext=mp4]/best",
        "--download-sections", f"*{start}-{end}",
        "--force-keyframes-at-cuts",
        "--quiet",
        "--no-warnings",
        "-o", str(temporary),
        url
    ]
    
    try:
        result = subprocess.run(command, capture_output=True, text=True, check=False)
        if result.returncode != 0:
            raise RuntimeError(f"yt-dlp failed: {compact_error(result.stderr)}")
        if not temporary.exists():
            raise RuntimeError("yt-dlp finished but output file is missing")
        temporary.replace(output_path)
    finally:
        if temporary.exists():
            temporary.unlink()


def main() -> int:
    args = parse_args()
    
    if not args.missing_csv.is_file():
        raise SystemExit(f"Missing videos CSV not found: {args.missing_csv}")

    ffprobe = shutil.which("ffprobe")
    yt_dlp = shutil.which("yt-dlp")
    
    if not ffprobe:
        raise SystemExit("ffprobe was not found in PATH")
    if not yt_dlp:
        raise SystemExit("yt-dlp was not found in PATH. Please run 'pip install yt-dlp'")

    requests: list[MissingRequest] = []
    seen_filenames = set()
    
    with args.missing_csv.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            video_id = row.get("youtube_id")
            k_filename = row.get("kinetics_filename")
            
            if not video_id or not k_filename:
                continue
                
            expected_filename = f"{k_filename}.mp4"
            if expected_filename in seen_filenames:
                continue
                
            try:
                parts = k_filename.split("_")
                start_sec = int(parts[-2])
                end_sec = int(parts[-1])
            except (ValueError, IndexError):
                continue
            
            seen_filenames.add(expected_filename)
            requests.append(MissingRequest(
                split=row.get("split", "unknown"),
                video_id=video_id,
                start=start_sec,
                end=end_sec,
                expected_filename=expected_filename,
                kinetics_filename=k_filename
            ))

    print(f"Loaded {len(requests)} missing videos to download.")

    args.videos_dir.mkdir(parents=True, exist_ok=True)
    
    final_video_report = args.reports_dir / "final_missing_videos.csv"
    video_failures: list[dict[str, str]] = []
    
    success_videos = 0

    for position, req in enumerate(requests, start=1):
        prefix = f"[{position}/{len(requests)}] {req.split}/{req.video_id}"
        video_dest = args.videos_dir / req.expected_filename
        youtube_url = f"https://www.youtube.com/watch?v={req.video_id}"

        # 1. Download
        if not video_dest.is_file():
            print(f"{prefix}: downloading {req.start}s - {req.end}s ...", end="", flush=True)
            try:
                download_clip(yt_dlp, req.video_id, req.start, req.end, video_dest)
                print(" done.", flush=True)
                time.sleep(random.uniform(args.min_delay, args.max_delay))
            except Exception as exc:
                print(f" error: {exc}", flush=True)
                video_failures.append({
                    "split": req.split,
                    "youtube_id": req.video_id,
                    "kinetics_filename": req.kinetics_filename,
                    "expected_filename": req.expected_filename,
                    "source_path": youtube_url,
                    "reason": str(exc),
                })
                time.sleep(random.uniform(2.0, 4.0))
                continue
        else:
            print(f"{prefix}: video already exists, skipping download.", flush=True)

        # 2. Validate Video
        try:
            probe = probe_media(video_dest, ffprobe)
            if probe.video_streams == 0:
                raise ValueError("Downloaded file has no video stream")
        except Exception as exc:
            print(f"{prefix}: invalid video: {exc}", flush=True)
            if video_dest.exists():
                video_dest.unlink()
            
            video_failures.append({
                "split": req.split,
                "youtube_id": req.video_id,
                "kinetics_filename": req.kinetics_filename,
                "expected_filename": req.expected_filename,
                "source_path": youtube_url,
                "reason": f"Validation failed: {exc}",
            })
            continue

        success_videos += 1

    if video_failures:
        write_report(final_video_report, VIDEO_REPORT_COLUMNS, video_failures)
    elif final_video_report.exists():
        final_video_report.unlink()

    print("\n--- Summary ---")
    print(f"Total requests processed: {len(requests)}")
    print(f"Successfully processed valid videos: {success_videos}")
    print(f"Final missing videos: {len(video_failures)}" + (f" ({final_video_report.name})" if video_failures else ""))
    
    return 0 if not video_failures else 1


if __name__ == "__main__":
    sys.exit(main())