#!/usr/bin/env python3
"""Download locally missing Countix clips from YouTube.

Expected project layout::

    project/
    ├── download_missing_countix_videos_20260925_v2.py
    ├── missing_videos.csv
    ├── videos/
    └── final_missing_videos.csv

The input report is produced by ``get_countix_videos_20260925_v1.py`` and must
contain ``video_id``, ``kinetics_start`` and ``kinetics_end``. A row such as
video_id=dyzWet-ZFx4, start=78 and end=88 is downloaded as
``videos/dyzWet-ZFx4_000078_000088.mp4``.

Every valid input row is processed independently. The script is safe to resume:
valid existing clips are skipped, invalid files are removed and downloaded
again, downloads are written to temporary files, and remaining failures are
recorded in ``final_missing_videos.csv``.
"""

from __future__ import annotations

import argparse
import csv
import json
import random
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation
from pathlib import Path


SCRIPT_VERSION = "2.0"
SCRIPT_DIR = Path(__file__).resolve().parent
REQUIRED_COLUMNS = ("video_id", "kinetics_start", "kinetics_end")
MISSING_COLUMNS = (
    "split",
    "video_id",
    "kinetics_start",
    "kinetics_end",
    "kinetics_filename",
    "expected_filename",
    "youtube_url",
    "reason",
)


@dataclass
class DownloadRequest:
    split: str
    video_id: str
    start: int
    end: int
    kinetics_filename: str
    expected_filename: str


@dataclass(frozen=True)
class MediaProbe:
    duration: float | None
    video_streams: int
    video_codecs: tuple[str, ...]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Read missing_videos.csv and download the corresponding precise "
            "YouTube intervals using Kinetics-style filenames."
        )
    )
    parser.add_argument(
        "--missing-csv",
        type=Path,
        default=SCRIPT_DIR / "missing_videos.csv",
        help="Input report generated by the local-search script",
    )
    parser.add_argument(
        "--videos-dir",
        type=Path,
        default=SCRIPT_DIR / "videos",
        help="Output directory (default: videos/ beside this script)",
    )
    parser.add_argument(
        "--final-missing-csv",
        type=Path,
        default=SCRIPT_DIR / "final_missing_videos.csv",
        help=(
            "Remaining-failure report "
            "(default: final_missing_videos.csv beside this script)"
        ),
    )
    parser.add_argument(
        "--min-delay",
        type=float,
        default=4.0,
        help="Minimum random delay after a YouTube request",
    )
    parser.add_argument(
        "--max-delay",
        type=float,
        default=9.0,
        help="Maximum random delay after a YouTube request",
    )
    parser.add_argument(
        "--duration-tolerance",
        type=float,
        default=2.5,
        help="Maximum allowed duration error in seconds",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Download again even when a valid destination already exists",
    )
    parser.add_argument(
        "--cookies",
        type=Path,
        default=None,
        help="Optional Netscape-format cookies file passed to yt-dlp",
    )
    parser.add_argument(
        "--cookies-from-browser",
        default=None,
        metavar="BROWSER",
        help="Optional browser name passed to yt-dlp, for example firefox",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Process only the first N missing-video rows (useful for testing)",
    )
    return parser.parse_args()


def compact_error(text: str, limit: int = 1500) -> str:
    cleaned = " ".join(text.strip().split())
    return cleaned[-limit:] if cleaned else "unknown error"


def parse_integer_seconds(value: str, column: str) -> int:
    """Accept values such as 78 or 78.0, but reject fractional boundaries."""
    text = str(value).strip()
    if not text:
        raise ValueError(f"empty {column}")
    try:
        decimal = Decimal(text)
    except InvalidOperation as exc:
        raise ValueError(f"invalid {column}: {value!r}") from exc
    integral = decimal.to_integral_value()
    if decimal != integral:
        raise ValueError(
            f"{column} must be an integer number of seconds, received {value!r}"
        )
    seconds = int(integral)
    if seconds < 0:
        raise ValueError(f"{column} must be non-negative, received {seconds}")
    return seconds


def validate_video_id(value: str) -> str:
    video_id = str(value).strip()
    if not video_id:
        raise ValueError("empty video_id")
    if video_id in {".", ".."} or "/" in video_id or "\\" in video_id:
        raise ValueError(f"unsafe video_id: {video_id!r}")
    return video_id


def kinetics_stem(video_id: str, start: int, end: int) -> str:
    return f"{video_id}_{start:06d}_{end:06d}"


def youtube_url(video_id: str) -> str:
    return f"https://www.youtube.com/watch?v={video_id}"


def missing_row(
    *,
    split: str,
    video_id: str,
    start: str | int,
    end: str | int,
    kinetics_filename: str,
    expected_filename: str,
    reason: str,
) -> dict[str, str]:
    return {
        "split": split,
        "video_id": str(video_id),
        "kinetics_start": str(start),
        "kinetics_end": str(end),
        "kinetics_filename": kinetics_filename,
        "expected_filename": expected_filename,
        "youtube_url": youtube_url(str(video_id)) if str(video_id).strip() else "",
        "reason": reason,
    }


def read_requests(
    missing_csv: Path,
) -> tuple[list[DownloadRequest], list[dict[str, str]]]:
    """Read every row from the missing-video report without deduplication."""
    requests: list[DownloadRequest] = []
    failures: list[dict[str, str]] = []

    if not missing_csv.is_file():
        raise FileNotFoundError(f"Missing input report: {missing_csv}")

    with missing_csv.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            raise ValueError(f"CSV has no header: {missing_csv}")
        missing = set(REQUIRED_COLUMNS) - set(reader.fieldnames)
        if missing:
            raise ValueError(
                f"{missing_csv.name} is missing columns {sorted(missing)}. "
                f"Available columns: {reader.fieldnames}"
            )

        for line_number, row in enumerate(reader, start=2):
            split = str(row.get("split", "unknown") or "unknown").strip()
            raw_video_id = row.get("video_id", "")
            raw_start = row.get("kinetics_start", "")
            raw_end = row.get("kinetics_end", "")
            try:
                video_id = validate_video_id(raw_video_id)
                start = parse_integer_seconds(raw_start, "kinetics_start")
                end = parse_integer_seconds(raw_end, "kinetics_end")
                if end <= start:
                    raise ValueError(
                        f"kinetics_end ({end}) must be greater than "
                        f"kinetics_start ({start})"
                    )
                stem = kinetics_stem(video_id, start, end)
                expected_filename = stem + ".mp4"
            except ValueError as error:
                failures.append(
                    missing_row(
                        split=split,
                        video_id=raw_video_id,
                        start=raw_start,
                        end=raw_end,
                        kinetics_filename="",
                        expected_filename="",
                        reason=f"{missing_csv.name}:{line_number}: {error}",
                    )
                )
                continue

            requests.append(
                DownloadRequest(
                    split=split,
                    video_id=video_id,
                    start=start,
                    end=end,
                    kinetics_filename=stem,
                    expected_filename=expected_filename,
                )
            )

    return requests, failures


def probe_media(path: Path, ffprobe: str) -> MediaProbe:
    command = [
        ffprobe,
        "-v",
        "error",
        "-show_entries",
        "format=duration:stream=codec_type,codec_name",
        "-of",
        "json",
        str(path),
    ]
    result = subprocess.run(command, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(f"ffprobe failed: {compact_error(result.stderr)}")
    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError("ffprobe returned invalid JSON") from exc

    streams = payload.get("streams", [])
    video_codecs = tuple(
        str(stream.get("codec_name", "unknown"))
        for stream in streams
        if stream.get("codec_type") == "video"
    )
    duration_value = payload.get("format", {}).get("duration")
    try:
        duration = float(duration_value) if duration_value is not None else None
    except (TypeError, ValueError):
        duration = None

    return MediaProbe(
        duration=duration,
        video_streams=len(video_codecs),
        video_codecs=video_codecs,
    )


def validate_clip(
    path: Path,
    request: DownloadRequest,
    ffprobe: str,
    duration_tolerance: float,
) -> MediaProbe:
    probe = probe_media(path, ffprobe)
    if probe.video_streams < 1:
        raise ValueError("file has no video stream")
    if probe.duration is None or probe.duration <= 0:
        raise ValueError("file has no valid duration")

    expected_duration = request.end - request.start
    if abs(probe.duration - expected_duration) > duration_tolerance:
        raise ValueError(
            f"duration is {probe.duration:.3f}s; expected approximately "
            f"{expected_duration}s (tolerance {duration_tolerance}s)"
        )
    return probe


def write_missing_report(path: Path, rows: list[dict[str, str]]) -> None:
    """Atomically write the report, including its header when no rows failed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=MISSING_COLUMNS)
        writer.writeheader()
        writer.writerows(rows)
    temporary.replace(path)


def download_clip(
    *,
    request: DownloadRequest,
    destination: Path,
    yt_dlp: str,
    cookies: Path | None,
    cookies_from_browser: str | None,
) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(
        f".{destination.stem}.downloading{destination.suffix}"
    )
    temporary.unlink(missing_ok=True)

    command = [
        yt_dlp,
        "--no-playlist",
        "--retries",
        "3",
        "--fragment-retries",
        "3",
        "--download-sections",
        f"*{request.start}-{request.end}",
        "--force-keyframes-at-cuts",
        "-f",
        "bestvideo[ext=mp4]/bestvideo",
        "--remux-video",
        "mp4",
        "--quiet",
        "--no-warnings",
        "-o",
        str(temporary),
    ]
    if cookies is not None:
        command.extend(["--cookies", str(cookies)])
    if cookies_from_browser:
        command.extend(["--cookies-from-browser", cookies_from_browser])
    command.append(youtube_url(request.video_id))

    try:
        result = subprocess.run(command, capture_output=True, text=True, check=False)
        if result.returncode != 0:
            details = result.stderr or result.stdout
            raise RuntimeError(f"yt-dlp failed: {compact_error(details)}")
        if not temporary.is_file():
            raise RuntimeError("yt-dlp finished but the temporary MP4 is missing")
        temporary.replace(destination)
    finally:
        temporary.unlink(missing_ok=True)


def main() -> int:
    args = parse_args()
    if args.min_delay < 0 or args.max_delay < args.min_delay:
        raise SystemExit("Require 0 <= --min-delay <= --max-delay")
    if args.duration_tolerance < 0:
        raise SystemExit("--duration-tolerance must be non-negative")
    if args.limit is not None and args.limit < 1:
        raise SystemExit("--limit must be a positive integer")

    missing_csv = args.missing_csv.expanduser().resolve()
    videos_dir = args.videos_dir.expanduser().resolve()
    final_missing_csv = args.final_missing_csv.expanduser().resolve()
    cookies = args.cookies.expanduser().resolve() if args.cookies else None

    if missing_csv == final_missing_csv:
        raise SystemExit(
            "--missing-csv and --final-missing-csv must refer to different files"
        )

    ffprobe = shutil.which("ffprobe")
    yt_dlp = shutil.which("yt-dlp")
    if ffprobe is None:
        raise SystemExit("ffprobe was not found in PATH; install FFmpeg first")
    if yt_dlp is None:
        raise SystemExit("yt-dlp was not found; install it with: pip install yt-dlp")
    if cookies is not None and not cookies.is_file():
        raise SystemExit(f"Cookies file does not exist: {cookies}")

    try:
        requests, failures = read_requests(missing_csv)
    except (FileNotFoundError, ValueError) as error:
        raise SystemExit(str(error)) from error

    requests.sort(key=lambda item: item.expected_filename)
    if args.limit is not None:
        requests = requests[: args.limit]

    videos_dir.mkdir(parents=True, exist_ok=True)
    write_missing_report(final_missing_csv, failures)

    print(f"Script version: {SCRIPT_VERSION}")
    print(f"Input missing report: {missing_csv}")
    print(f"Videos directory: {videos_dir}")
    print(f"Missing-video rows to process: {len(requests)}")
    if failures:
        print(f"Invalid input rows: {len(failures)}")

    valid_count = 0
    downloaded_count = 0
    existing_count = 0

    for position, request in enumerate(requests, start=1):
        prefix = (
            f"[{position}/{len(requests)}] "
            f"{request.split}/{request.expected_filename}"
        )
        destination = videos_dir / request.expected_filename

        if destination.is_file() and not args.overwrite:
            try:
                validate_clip(
                    destination,
                    request,
                    ffprobe,
                    args.duration_tolerance,
                )
                print(f"{prefix}: valid file already exists; skipping")
                valid_count += 1
                existing_count += 1
                continue
            except Exception as error:
                print(f"{prefix}: existing file is invalid ({error}); deleting")
                destination.unlink(missing_ok=True)

        print(
            f"{prefix}: downloading {request.start}s–{request.end}s...",
            end="",
            flush=True,
        )
        failure: dict[str, str] | None = None
        try:
            download_clip(
                request=request,
                destination=destination,
                yt_dlp=yt_dlp,
                cookies=cookies,
                cookies_from_browser=args.cookies_from_browser,
            )
            probe = validate_clip(
                destination,
                request,
                ffprobe,
                args.duration_tolerance,
            )
            print(
                f" done ({probe.duration:.2f}s, "
                f"video={','.join(probe.video_codecs)})."
            )
            valid_count += 1
            downloaded_count += 1
        except Exception as error:
            destination.unlink(missing_ok=True)
            print(f" failed: {error}")
            failure = missing_row(
                split=request.split,
                video_id=request.video_id,
                start=request.start,
                end=request.end,
                kinetics_filename=request.kinetics_filename,
                expected_filename=request.expected_filename,
                reason=str(error),
            )

        if failure is not None:
            failures.append(failure)
        write_missing_report(final_missing_csv, failures)

        delay = random.uniform(args.min_delay, args.max_delay)
        if delay > 0:
            time.sleep(delay)

    print("\n--- Summary ---")
    print(f"Missing-video rows considered: {len(requests)}")
    print(f"Valid clips: {valid_count}")
    print(f"Downloaded in this run: {downloaded_count}")
    print(f"Already present: {existing_count}")
    print(f"Missing/failed rows: {len(failures)}")
    print(f"Final missing report: {final_missing_csv}")

    return 0 if not failures else 1


if __name__ == "__main__":
    sys.exit(main())
