#!/usr/bin/env python3
"""Download missing CountixAV videos from YouTube using yt-dlp.

This script reads missing_videos.csv, attempts to download the precise
segments from YouTube, saves the video to videos/ and extracts the audio
to audios/. It implements random delays between downloads to avoid
rate-limiting, and outputs final_missing_videos.csv and
final_audio_extraction_failures.csv for any clips that still fail.
It immediately deletes any downloaded video if it is corrupted or if its
audio cannot be extracted, ensuring no orphaned files are left on disk.
"""

import argparse
import csv
import json
import random
import shutil
import subprocess
import sys
import time
import wave
from dataclasses import dataclass
from pathlib import Path


SCRIPT_VERSION = "1.1"
SCRIPT_DIR = Path(__file__).resolve().parent

VIDEO_REPORT_COLUMNS = (
    "split",
    "video_id",
    "kinetics_start",
    "kinetics_end",
    "expected_filename",
    "source_path",
    "reason",
)
AUDIO_REPORT_COLUMNS = (
    "split",
    "video_id",
    "kinetics_start",
    "kinetics_end",
    "source_path",
    "audio_path",
    "reason",
)


@dataclass(frozen=True)
class MissingRequest:
    split: str
    video_id: str
    start: float
    end: float
    expected_filename: str


@dataclass(frozen=True)
class MediaProbe:
    duration: float | None
    video_streams: int
    audio_streams: int
    video_codecs: tuple[str, ...]
    audio_codecs: tuple[str, ...]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Download missing CountixAV clips from YouTube."
    )
    parser.add_argument(
        "--missing-csv",
        type=Path,
        default=SCRIPT_DIR / "missing_videos.csv",
        help="Path to the missing_videos.csv file generated by the first script",
    )
    parser.add_argument(
        "--videos-dir",
        type=Path,
        default=SCRIPT_DIR / "videos",
        help="Video output directory (default: <script_dir>/videos)",
    )
    parser.add_argument(
        "--audios-dir",
        type=Path,
        default=SCRIPT_DIR / "audios",
        help="Audio output directory (default: <script_dir>/audios)",
    )
    parser.add_argument(
        "--reports-dir",
        type=Path,
        default=SCRIPT_DIR,
        help="CSV report directory for final_* files (default: <script_dir>)",
    )
    parser.add_argument(
        "--sample-rate",
        type=int,
        default=16_000,
        help="WAV sample rate in Hz (default: 16000)",
    )
    parser.add_argument(
        "--min-delay",
        type=float,
        default=4.0,
        help="Minimum delay in seconds between YouTube requests",
    )
    parser.add_argument(
        "--max-delay",
        type=float,
        default=9.0,
        help="Maximum delay in seconds between YouTube requests",
    )
    return parser.parse_args()


def compact_error(text: str, limit: int = 1200) -> str:
    cleaned = " ".join(text.strip().split())
    return cleaned[-limit:] if cleaned else "unknown error"


def probe_media(path: Path, ffprobe: str) -> MediaProbe:
    command = [
        ffprobe,
        "-v",
        "error",
        "-show_entries",
        "format=duration:stream=index,codec_type,codec_name,duration",
        "-of",
        "json",
        str(path),
    ]
    result = subprocess.run(command, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(f"ffprobe failed: {compact_error(result.stderr)}")
    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError("ffprobe returned invalid JSON") from exc

    streams = payload.get("streams", [])
    video_codecs = tuple(
        str(stream.get("codec_name", "unknown"))
        for stream in streams
        if stream.get("codec_type") == "video"
    )
    audio_codecs = tuple(
        str(stream.get("codec_name", "unknown"))
        for stream in streams
        if stream.get("codec_type") == "audio"
    )
    duration_value = payload.get("format", {}).get("duration")
    try:
        duration = float(duration_value) if duration_value is not None else None
    except (TypeError, ValueError):
        duration = None
    return MediaProbe(
        duration=duration,
        video_streams=len(video_codecs),
        audio_streams=len(audio_codecs),
        video_codecs=video_codecs,
        audio_codecs=audio_codecs,
    )


def valid_wav(path: Path, sample_rate: int) -> bool:
    if not path.is_file() or path.stat().st_size <= 44:
        return False
    try:
        with wave.open(str(path), "rb") as handle:
            return (
                handle.getnchannels() == 1
                and handle.getsampwidth() == 2
                and handle.getframerate() == sample_rate
                and handle.getnframes() > 0
            )
    except (OSError, wave.Error):
        return False


def extract_wav(
    source: Path,
    destination: Path,
    ffmpeg: str,
    sample_rate: int,
) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(f".{destination.stem}.extracting.wav")
    if temporary.exists():
        temporary.unlink()
    command = [
        ffmpeg,
        "-nostdin",
        "-hide_banner",
        "-loglevel",
        "error",
        "-y",
        "-i",
        str(source),
        "-map",
        "0:a:0",
        "-vn",
        "-ac",
        "1",
        "-ar",
        str(sample_rate),
        "-c:a",
        "pcm_s16le",
        str(temporary),
    ]
    try:
        result = subprocess.run(command, capture_output=True, text=True, check=False)
        if result.returncode != 0:
            raise RuntimeError(f"ffmpeg failed: {compact_error(result.stderr)}")
        if not valid_wav(temporary, sample_rate):
            raise RuntimeError("ffmpeg produced an invalid WAV file")
        temporary.replace(destination)
    finally:
        if temporary.exists():
            temporary.unlink()


def format_number(value: float) -> str:
    return str(int(value)) if value.is_integer() else f"{value:.6f}".rstrip("0").rstrip(".")


def write_report(
    path: Path,
    columns: tuple[str, ...],
    rows: list[dict[str, str]],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        writer.writerows(rows)
    temporary.replace(path)


def download_clip(
    yt_dlp: str,
    video_id: str,
    start: float,
    end: float,
    output_path: Path
) -> None:
    """Download a specific segment from YouTube using yt-dlp."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = output_path.with_name(f".{output_path.stem}.downloading{output_path.suffix}")
    if temporary.exists():
        temporary.unlink()

    url = f"https://www.youtube.com/watch?v={video_id}"
    
    command = [
        yt_dlp,
        "-f", "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best",
        "--download-sections", f"*{start}-{end}",
        "--force-keyframes-at-cuts",
        "--quiet",
        "--no-warnings",
        "-o", str(temporary),
        url
    ]
    
    try:
        result = subprocess.run(command, capture_output=True, text=True, check=False)
        if result.returncode != 0:
            raise RuntimeError(f"yt-dlp failed: {compact_error(result.stderr)}")
        if not temporary.exists():
            raise RuntimeError("yt-dlp finished but output file is missing")
        temporary.replace(output_path)
    finally:
        if temporary.exists():
            temporary.unlink()


def main() -> int:
    args = parse_args()
    
    if not args.missing_csv.is_file():
        raise SystemExit(f"Missing videos CSV not found: {args.missing_csv}")

    ffprobe = shutil.which("ffprobe")
    ffmpeg = shutil.which("ffmpeg")
    yt_dlp = shutil.which("yt-dlp")
    
    if not ffprobe:
        raise SystemExit("ffprobe was not found in PATH")
    if not ffmpeg:
        raise SystemExit("ffmpeg was not found in PATH")
    if not yt_dlp:
        raise SystemExit("yt-dlp was not found in PATH. Please run 'pip install yt-dlp'")

    requests: list[MissingRequest] = []
    with args.missing_csv.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            if not row.get("video_id"):
                continue
            try:
                start = float(row["kinetics_start"])
                end = float(row["kinetics_end"])
            except ValueError:
                continue
            
            requests.append(MissingRequest(
                split=row.get("split", "unknown"),
                video_id=row["video_id"],
                start=start,
                end=end,
                expected_filename=row["expected_filename"]
            ))

    print(f"Loaded {len(requests)} missing videos to download.")

    args.videos_dir.mkdir(parents=True, exist_ok=True)
    args.audios_dir.mkdir(parents=True, exist_ok=True)
    
    final_video_report = args.reports_dir / "final_missing_videos.csv"
    final_audio_report = args.reports_dir / "final_audio_extraction_failures.csv"
    
    video_failures: list[dict[str, str]] = []
    audio_failures: list[dict[str, str]] = []
    
    success_pairs = 0

    for position, req in enumerate(requests, start=1):
        prefix = f"[{position}/{len(requests)}] {req.split}/{req.video_id}"
        video_dest = args.videos_dir / req.expected_filename
        audio_stem = Path(req.expected_filename).stem
        audio_dest = args.audios_dir / f"{audio_stem}.wav"
        youtube_url = f"https://www.youtube.com/watch?v={req.video_id}"

        # 1. Download
        if not video_dest.is_file():
            print(f"{prefix}: downloading {req.start}s - {req.end}s ...", end="", flush=True)
            try:
                download_clip(yt_dlp, req.video_id, req.start, req.end, video_dest)
                print(" done.", flush=True)
                time.sleep(random.uniform(args.min_delay, args.max_delay))
            except Exception as exc:
                print(f" error: {exc}", flush=True)
                video_failures.append({
                    "split": req.split,
                    "video_id": req.video_id,
                    "kinetics_start": format_number(req.start),
                    "kinetics_end": format_number(req.end),
                    "expected_filename": req.expected_filename,
                    "source_path": youtube_url,
                    "reason": str(exc),
                })
                audio_failures.append({
                    "split": req.split,
                    "video_id": req.video_id,
                    "kinetics_start": format_number(req.start),
                    "kinetics_end": format_number(req.end),
                    "source_path": youtube_url,
                    "audio_path": "",
                    "reason": "video download failed",
                })
                time.sleep(random.uniform(2.0, 4.0))
                continue
        else:
            print(f"{prefix}: video already exists, skipping download.", flush=True)

        # 2. Validate Video
        try:
            probe = probe_media(video_dest, ffprobe)
            if probe.video_streams == 0:
                raise ValueError("Downloaded file has no video stream")
        except Exception as exc:
            print(f"{prefix}: invalid video: {exc}", flush=True)
            if video_dest.exists():
                video_dest.unlink()
            
            video_failures.append({
                "split": req.split,
                "video_id": req.video_id,
                "kinetics_start": format_number(req.start),
                "kinetics_end": format_number(req.end),
                "expected_filename": req.expected_filename,
                "source_path": youtube_url,
                "reason": f"Validation failed: {exc}",
            })
            audio_failures.append({
                "split": req.split,
                "video_id": req.video_id,
                "kinetics_start": format_number(req.start),
                "kinetics_end": format_number(req.end),
                "source_path": youtube_url,
                "audio_path": "",
                "reason": "video was invalid/corrupted",
            })
            continue

        # 3. Extract Audio
        if not valid_wav(audio_dest, args.sample_rate):
            if probe.audio_streams == 0:
                print(f"{prefix}: source has no audio stream. Removing video.", flush=True)
                if video_dest.exists():
                    video_dest.unlink()
                audio_failures.append({
                    "split": req.split,
                    "video_id": req.video_id,
                    "kinetics_start": format_number(req.start),
                    "kinetics_end": format_number(req.end),
                    "source_path": str(video_dest),
                    "audio_path": str(audio_dest),
                    "reason": "downloaded video has no audio stream",
                })
            else:
                try:
                    extract_wav(video_dest, audio_dest, ffmpeg, args.sample_rate)
                    success_pairs += 1
                except Exception as exc:
                    print(f"{prefix}: audio extraction failed: {exc}. Removing video.", flush=True)
                    if video_dest.exists():
                        video_dest.unlink()
                    audio_failures.append({
                        "split": req.split,
                        "video_id": req.video_id,
                        "kinetics_start": format_number(req.start),
                        "kinetics_end": format_number(req.end),
                        "source_path": str(video_dest),
                        "audio_path": str(audio_dest),
                        "reason": str(exc),
                    })
        else:
            success_pairs += 1

    write_report(final_video_report, VIDEO_REPORT_COLUMNS, video_failures)
    write_report(final_audio_report, AUDIO_REPORT_COLUMNS, audio_failures)

    print("\n--- Summary ---")
    print(f"Total requests processed: {len(requests)}")
    print(f"Successfully processed valid video/audio pairs: {success_pairs}")
    print(f"Final missing videos: {len(video_failures)} ({final_video_report})")
    print(f"Final audio failures: {len(audio_failures)} ({final_audio_report})")
    
    return 0 if not video_failures and not audio_failures else 1


if __name__ == "__main__":
    sys.exit(main())